name = "Advent2022"
uuid = "1f9ee42e-20ca-47a1-a4ca-67ac0ad55f6e"
authors = ["Jonnie Diegelman <jonniediegelman@gmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
EventUtils = "8ae8ae43-0fe5-488b-a1b4-37edb6aad1d2"
